### ISSUE TITLE
Allowed Field Doesn' Work

### ISSUE THREAD

**Issue by didikkoetoe** [jesperbjerke/laravel-api-query-builder#4]
Sorry if my English is bad, hope you can understand.

Here there is a problem with the select query, where if you set allowedApiFields, the default query should be that in the request. Because for now, if the select query is not there, then the default is *, finally the data that is not allowed to be selected is still visible.

**Comment by jesperbjerke** [comment]
Hello! I am not actively maintaining this package any longer. And since I started building this, there has popped up other alternatives which now also has a larger user base and bigger team behind it. I suggest looking into this one: https://github.com/spatie/laravel-query-builder

If not, if you submit a PR I'll be happy to review it.
